INSERT INTO Alergen (nazivAlergena) VALUES
('Peanuts'),
('Soybeans'),
('Milk'),
('Eggs'),
('Fish'),
('Crustaceans'),
('Molluscs'),
('Wheat (gluten)'),
('Tree nuts - almond'),
('Tree nuts - hazelnut'),
('Tree nuts - walnut'),
('Tree nuts - cashew'),
('Tree nuts - pistachio'),
('Tree nuts - Brazil nut'),
('Tree nuts - macadamia'),
('Sesame'),
('Celery'),
('Mustard'),
('Sulphur dioxide and sulphites'),
('Lupin');

INSERT INTO Sastojak (nazivSastojka) VALUES
-- Allergens (20)
('Peanuts'),
('Soybeans'),
('Milk'),
('Eggs'),
('Fish'),
('Crustaceans'),
('Molluscs'),
('Wheat (gluten)'),
('Tree nuts - almond'),
('Tree nuts - hazelnut'),
('Tree nuts - walnut'),
('Tree nuts - cashew'),
('Tree nuts - pistachio'),
('Tree nuts - Brazil nut'),
('Tree nuts - macadamia'),
('Sesame'),
('Celery'),
('Mustard'),
('Sulphur dioxide and sulphites'),
('Lupin'),

-- Meats
('Chicken breast'),
('Chicken thigh'),
('Beef steak'),
('Beef mince'),
('Pork loin'),
('Pork ribs'),
('Lamb chops'),
('Duck breast'),
('Turkey breast'),
('Ham'),
('Bacon'),
('Salami'),
('Prosciutto'),
('Sausage'),
('Chorizo'),
('Hot dog sausage'),
('Veal cutlet'),
('Goat meat'),
('Rabbit meat'),
('Venison'),

-- Fish & seafood (besides allergens)
('Tuna'),
('Salmon'),
('Trout'),
('Cod'),
('Mackerel'),
('Sardines'),
('Anchovies'),
('Octopus'),
('Squid'),
('Clams'),
('Oysters'),
('Scallops'),
('Lobster'),
('Crab'),
('Prawns'),

-- Dairy
('Cheddar cheese'),
('Mozzarella'),
('Parmesan'),
('Gorgonzola'),
('Blue cheese'),
('Cream cheese'),
('Ricotta'),
('Feta cheese'),
('Yogurt'),
('Butter'),
('Cream'),
('Sour cream'),
('Whipped cream'),
('Condensed milk'),
('Powdered milk'),

-- Vegetables
('Tomato'),
('Cherry tomato'),
('Cucumber'),
('Bell pepper'),
('Chili pepper'),
('Onion'),
('Red onion'),
('Garlic'),
('Leek'),
('Carrot'),
('Potato'),
('Sweet potato'),
('Spinach'),
('Lettuce'),
('Iceberg lettuce'),
('Kale'),
('Cabbage'),
('Broccoli'),
('Cauliflower'),
('Zucchini'),
('Eggplant'),
('Pumpkin'),
('Green beans'),
('Peas'),
('Corn'),
('Asparagus'),
('Mushrooms'),
('Champignon'),
('Portobello'),
('Shiitake'),

-- Fruits
('Apple'),
('Pear'),
('Banana'),
('Orange'),
('Mandarin'),
('Lemon'),
('Lime'),
('Grapefruit'),
('Strawberry'),
('Raspberry'),
('Blueberry'),
('Blackberry'),
('Cherry'),
('Sour cherry'),
('Plum'),
('Peach'),
('Apricot'),
('Grape'),
('Watermelon'),
('Melon'),
('Kiwi'),
('Pineapple'),
('Mango'),
('Papaya'),
('Coconut'),
('Pomegranate'),

-- Grains & legumes
('Rice'),
('Brown rice'),
('Basmati rice'),
('Couscous'),
('Quinoa'),
('Barley'),
('Oats'),
('Rye'),
('Buckwheat'),
('Millet'),
('Chickpeas'),
('Lentils'),
('Green lentils'),
('Red lentils'),
('Kidney beans'),
('Black beans'),
('White beans'),

-- Oils, spices & condiments
('Olive oil'),
('Sunflower oil'),
('Canola oil'),
('Coconut oil'),
('Sesame oil'),
('Vinegar'),
('Apple cider vinegar'),
('Balsamic vinegar'),
('Soy sauce'),
('Fish sauce'),
('Worcestershire sauce'),
('Ketchup'),
('Mayonnaise'),
('Mustard seeds'),
('Honey'),
('Sugar'),
('Brown sugar'),
('Salt'),
('Sea salt'),
('Pepper'),
('Black pepper'),
('White pepper'),
('Paprika'),
('Cayenne pepper'),
('Curry powder'),
('Turmeric'),
('Cumin'),
('Coriander'),
('Basil'),
('Oregano'),
('Rosemary'),
('Thyme'),
('Parsley'),
('Dill'),
('Mint'),
('Ginger'),
('Cinnamon'),
('Nutmeg'),
('Cloves'),
('Cardamom'),

-- Bakery & pasta
('White bread'),
('Wholegrain bread'),
('Baguette'),
('Tortilla'),
('Noodles'),
('Spaghetti'),
('Macaroni'),
('Lasagna sheets'),
('Pizza dough'),
('Croissant');

INSERT INTO Jelo (nazivJela, cena, slika, vremePripreme, brojPorudzbina) VALUES
('Spaghetti Bolognese', 12, 'spaghetti_bolognese.png', 35, 0),
('Chicken Caesar Salad', 10, 'chicken_caesar_salad.png', 20, 0),
('Margherita Pizza', 9, 'margherita_pizza.png', 25, 0),
('Pepperoni Pizza', 11, 'pepperoni_pizza.png', 25, 0),
('Four Cheese Pizza', 13, 'four_cheese_pizza.png', 25, 0),
('Pasta Carbonara', 12, 'pasta_carbonara.png', 30, 0),
('Lasagna', 14, 'lasagna.png', 40, 0),
('Mushroom Risotto', 12, 'mushroom_risotto.png', 35, 0),
('Grilled Salmon', 16, 'grilled_salmon.png', 25, 0),
('Fish and Chips', 11, 'fish_and_chips.png', 30, 0),
('Shrimp Scampi', 15, 'shrimp_scampi.png', 25, 0),
('Seafood Paella', 18, 'seafood_paella.png', 45, 0),
('Beef Burger', 11, 'beef_burger.png', 20, 0),
('Cheeseburger', 12, 'cheeseburger.png', 20, 0),
('Veggie Burger', 10, 'veggie_burger.png', 20, 0),
('Hot Dog', 8, 'hot_dog.png', 15, 0),
('Club Sandwich', 9, 'club_sandwich.png', 15, 0),
('BLT Sandwich', 9, 'blt_sandwich.png', 15, 0),
('Grilled Cheese Sandwich', 7, 'grilled_cheese_sandwich.png', 10, 0),
('Chicken Wrap', 8, 'chicken_wrap.png', 15, 0),
('Falafel Wrap', 8, 'falafel_wrap.png', 15, 0),
('Beef Tacos', 10, 'beef_tacos.png', 20, 0),
('Chicken Tacos', 10, 'chicken_tacos.png', 20, 0),
('Fish Tacos', 11, 'fish_tacos.png', 20, 0),
('Vegetarian Tacos', 9, 'vegetarian_tacos.png', 20, 0),
('Chicken Curry', 13, 'chicken_curry.png', 35, 0),
('Lamb Curry', 15, 'lamb_curry.png', 40, 0),
('Vegetable Curry', 12, 'vegetable_curry.png', 30, 0),
('Butter Chicken', 14, 'butter_chicken.png', 35, 0),
('Chicken Kebab', 12, 'chicken_kebab.png', 25, 0),
('Beef Kebab', 13, 'beef_kebab.png', 25, 0),
('Shawarma', 11, 'shawarma.png', 20, 0),
('Gyro', 10, 'gyro.png', 20, 0),
('Sushi Roll Salmon', 14, 'sushi_roll_salmon.png', 30, 0),
('Sushi Roll Tuna', 15, 'sushi_roll_tuna.png', 30, 0),
('Sushi Roll Avocado', 12, 'sushi_roll_avocado.png', 25, 0),
('Tempura Shrimp', 13, 'tempura_shrimp.png', 25, 0),
('Pad Thai', 14, 'pad_thai.png', 30, 0),
('Spring Rolls', 8, 'spring_rolls.png', 15, 0),
('Sweet and Sour Pork', 13, 'sweet_and_sour_pork.png', 25, 0),
('Kung Pao Chicken', 14, 'kung_pao_chicken.png', 30, 0),
('Fried Rice', 10, 'fried_rice.png', 20, 0),
('Beef Noodles', 12, 'beef_noodles.png', 25, 0),
('Chicken Noodles', 11, 'chicken_noodles.png', 25, 0),
('Vegetable Stir Fry', 10, 'vegetable_stir_fry.png', 20, 0),
('Ramen', 13, 'ramen.png', 30, 0),
('Pho', 14, 'pho.png', 35, 0),
('Beef Steak', 18, 'beef_steak.png', 40, 0),
('Pork Chops', 15, 'pork_chops.png', 35, 0),
('Grilled Chicken Breast', 12, 'grilled_chicken_breast.png', 25, 0);
